export const mcpServers = [
  { slug: "github", name: "GitHub MCP", sourceUrl: "https://github.com/github/github-mcp-server", status: "source-linked", note: "Canonical source should be verified before feature-level publication." },
  { slug: "postgres", name: "PostgreSQL MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "slack", name: "Slack MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "filesystem", name: "Filesystem MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "notion", name: "Notion MCP", sourceUrl: "https://github.com/makenotion/notion-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "excel", name: "Excel MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy URL retained while a canonical upstream is verified." },
  { slug: "shopify", name: "Shopify MCP", sourceUrl: "https://shopify.dev/", status: "refreshing", note: "Legacy URL retained while an official MCP source is verified." },
  { slug: "google-drive", name: "Google Drive MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "google-maps", name: "Google Maps MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "brave-search", name: "Brave Search MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "puppeteer", name: "Puppeteer MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "memory", name: "Memory MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for a knowledge-graph-backed persistent memory server." },
  { slug: "gitlab", name: "GitLab MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "sentry", name: "Sentry MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for error-tracking data access." },
  { slug: "cloudflare", name: "Cloudflare MCP", sourceUrl: "https://github.com/cloudflare/mcp-server-cloudflare", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "sqlite", name: "SQLite MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage; verify current package/source before deployment." },
  { slug: "fetch", name: "Fetch MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for web content fetching and conversion." },
  { slug: "time", name: "Time MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for timezone conversion utilities." },
  { slug: "redis", name: "Redis MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "aws-kb-retrieval", name: "AWS Knowledge Base Retrieval MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for Bedrock knowledge base retrieval." },
  { slug: "everart", name: "EverArt MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "linear-mcp", name: "Linear MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for Linear issue tracking." },
  { slug: "context7", name: "Context7 MCP", sourceUrl: "https://github.com/upstash/context7", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "playwright-mcp", name: "Playwright MCP", sourceUrl: "https://github.com/microsoft/playwright-mcp", status: "source-linked", note: "First-party Microsoft repository link retained; capabilities should be read from upstream." },
  { slug: "docker-mcp", name: "Docker MCP", sourceUrl: "https://github.com/docker/mcp-servers", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "terraform-mcp", name: "Terraform MCP", sourceUrl: "https://github.com/hashicorp/terraform-mcp-server", status: "source-linked", note: "First-party HashiCorp repository link retained; capabilities should be read from upstream." },
  { slug: "asana-mcp", name: "Asana MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "todoist-mcp", name: "Todoist MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "obsidian-mcp", name: "Obsidian MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "everything-mcp", name: "Everything MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage used as a comprehensive test and demo server." },
  { slug: "sequential-thinking-mcp", name: "Sequential Thinking MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "source-linked", note: "Reference-server lineage for structured, step-by-step reasoning support." },
  { slug: "pinecone-mcp", name: "Pinecone MCP", sourceUrl: "https://github.com/pinecone-io/pinecone-mcp", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "stripe-mcp", name: "Stripe MCP", sourceUrl: "https://github.com/stripe/agent-toolkit", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "neon-mcp", name: "Neon MCP", sourceUrl: "https://github.com/neondatabase/mcp-server-neon", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "supabase-mcp", name: "Supabase MCP", sourceUrl: "https://github.com/supabase-community/supabase-mcp", status: "source-linked", note: "Community-maintained repository link retained; capabilities should be read from upstream." },
  { slug: "vercel-mcp", name: "Vercel MCP", sourceUrl: "https://vercel.com/docs/mcp", status: "source-linked", note: "First-party documentation link retained; capabilities should be read from upstream." },
  { slug: "hubspot-mcp", name: "HubSpot MCP", sourceUrl: "https://developers.hubspot.com/mcp", status: "source-linked", note: "First-party documentation link retained; capabilities should be read from upstream." },
  { slug: "grafana-mcp", name: "Grafana MCP", sourceUrl: "https://github.com/grafana/mcp-grafana", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "browserbase-mcp", name: "Browserbase MCP", sourceUrl: "https://github.com/browserbase/mcp-server-browserbase", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "firecrawl-mcp", name: "Firecrawl MCP", sourceUrl: "https://github.com/mendableai/firecrawl-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "apify-mcp", name: "Apify MCP", sourceUrl: "https://github.com/apify/actors-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "chroma-mcp", name: "Chroma MCP", sourceUrl: "https://github.com/chroma-core/chroma-mcp", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "heroku-mcp", name: "Heroku MCP", sourceUrl: "https://github.com/heroku/heroku-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "cloudinary-mcp", name: "Cloudinary MCP", sourceUrl: "https://github.com/cloudinary/mcp-servers", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "atlassian-mcp", name: "Atlassian MCP", sourceUrl: "https://www.atlassian.com/platform/remote-mcp-server", status: "source-linked", note: "First-party documentation link retained; capabilities should be read from upstream." },
  { slug: "elasticsearch-mcp", name: "Elasticsearch MCP", sourceUrl: "https://github.com/elastic/mcp-server-elasticsearch", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "snowflake-mcp", name: "Snowflake MCP", sourceUrl: "https://github.com/Snowflake-Labs/mcp", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "bigquery-mcp", name: "BigQuery MCP", sourceUrl: "https://github.com/googleapis/genai-toolbox", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "wikipedia-mcp", name: "Wikipedia MCP", sourceUrl: "https://github.com/modelcontextprotocol/servers", status: "refreshing", note: "Legacy route preserved; current maintained upstream needs verification." },
  { slug: "google-calendar-mcp", name: "Google Calendar MCP", sourceUrl: "https://github.com/nspady/google-calendar-mcp", status: "source-linked", note: "Community-maintained repository link retained; capabilities should be read from upstream." },
  { slug: "datadog-mcp", name: "Datadog MCP", sourceUrl: "https://github.com/DataDog/datadog-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "pagerduty-mcp", name: "PagerDuty MCP", sourceUrl: "https://github.com/PagerDuty/pagerduty-mcp-server", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "kagi-mcp", name: "Kagi MCP", sourceUrl: "https://github.com/kagisearch/kagimcp", status: "source-linked", note: "First-party repository link retained; capabilities should be read from upstream." },
  { slug: "duckduckgo-mcp", name: "DuckDuckGo MCP", sourceUrl: "https://github.com/nickclyde/duckduckgo-mcp-server", status: "source-linked", note: "Community-maintained repository link retained; capabilities should be read from upstream." }
] as const;

export const mcpClusters = [
  ["Core protocol", "Clients, servers, tools, resources, prompts, transports and authorization."],
  ["Server directory", "Source-linked MCP implementations with canonical upstreams."],
  ["Agent frameworks", "How frameworks expose or consume MCP without treating MCP as a framework replacement."],
  ["Local LLMs", "MCP with local inference, with performance claims held until reproducible benchmarks exist."],
  ["India", "Sovereignty, Indic-language workflows and DPDP-aware architecture without automatic compliance claims."]
] as const;
