import type { ContentBlock } from "@/components/ContentBlocks";

export type TrustPage = { title: string; description: string; blocks: ContentBlock[] };

export const trustPages: Record<string, TrustPage> = {
  "comparison-methodology": {
    title: "Comparison Methodology — How Head-to-Head Pages Are Constructed",
    description: "How BestAIAgent.in builds product comparison pages: equivalent evidence windows, declared weights, scenario recommendations, and reverse-route canonicalization.",
    blocks: [
      { type: "p", text: "Comparison pages are the most-trusted and the most-misused artefacts on a research site. This page documents how we build comparison pages, what evidence windows we require, and how we handle the reverse-direction (\"X vs. Y\") slug problem." },
      { type: "h2", text: "When we will publish a comparison page" },
      { type: "p", text: "We publish a comparison page only when both products under review have:" },
      { type: "ul", items: ["A primary source we can cite for at least the head-to-head criteria.", "Equivalent evidence windows (we do not compare today's evidence for product A against last year's evidence for product B).", "Comparable surface area in the comparison (we do not compare an enterprise plan against a hobby plan without saying so explicitly)."] },
      { type: "p", text: "When one side has thin evidence we either refuse to publish the page, narrow the comparison scope, or move the page to \`needs_more_research\`." },
      { type: "h2", text: "Evidence window parity" },
      { type: "p", text: "Every comparison page declares an evidence window (the date range of the receipts we relied on). If the windows are not equivalent — for example because product A was last reviewed on 2026-07-12 and product B was last reviewed on 2025-11-04 — we either re-verify the older side or note the asymmetry in the methodology section." },
      { type: "p", text: "We do not silently inherit older evidence to make a comparison look fresher than it is." },
      { type: "h2", text: "Declared weights and criteria" },
      { type: "p", text: "Every comparison page publishes:" },
      { type: "ul", items: ["The criteria being compared (e.g. reasoning, tool use, latency, India fit, enterprise scalability).", "The weight assigned to each criterion.", "The source for each numeric value.", "The freshness of each numeric value."] },
      { type: "p", text: "The criteria and weights are declared in the page's methodology section. We do not change weights to force a desired verdict." },
      { type: "h2", text: "Scenario recommendations" },
      { type: "p", text: "Comparison pages conclude with scenario recommendations (\"choose A when X, choose B when Y\"). The scenarios are evidence-backed; they are not sales pitches for either vendor." },
      { type: "h2", text: "Reverse-route canonicalization" },
      { type: "p", text: "For every comparison we choose one canonical direction (\"A vs. B\" wins, \"B vs. A\" 301s to \"A vs. B\"). The reverse-direction routes are listed in \`src/content/registry/content-registry.ts\` under \`CANONICAL_REDIRECTS\` and produce 301 status codes at the routing layer." },
      { type: "p", text: "The canonical direction rule applies regardless of search volume. We do not swap canonical direction to chase a keyword." },
      { type: "h2", text: "What comparison pages do not do" },
      { type: "ul", items: ["We do not declare a winner without a methodology. \"X is the best\" is rejected unless the methodology is published on the same page.", "We do not invent \`AggregateRating\`, \`Review\`, or numeric review-count schema. We never mark up a comparison page with a score that is not visible on the page.", "We do not include affiliate links inside the verdict. Affiliate disclosure lives on [](/trust/affiliate-disclosure) and is reproduced on every page that links to a commercial partner."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Source classification](/trust/source-classification)", "[Canonical overlay registry](https://github.com/CodesbyFebin/best-ai-agent/blob/main/src/content/registry/content-registry.ts)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/data/evidenceSchema.ts\` (\`EVIDENCE_RULES.COMPARISON\`, retrieved 2026-08-22). Defines the comparison evidence gate used by every comparison page.", "Internal — \`src/content/registry/content-registry.ts\` (\`CANONICAL_REDIRECTS\`, retrieved 2026-08-22). Declares the reverse-direction 301 redirects for A-vs-B routes."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "rating-methodology": {
    title: "Rating Methodology — How Numeric Scores Are Computed",
    description: "How BestAIAgent.in computes numeric ratings: seven dimensions, evidence gating, weight declaration, and what scores never mean.",
    blocks: [
      { type: "p", text: "Numeric scores appear on entity profiles and comparison pages. This page documents how those scores are computed, what they do and do not mean, and what we refuse to score." },
      { type: "h2", text: "Where scores come from" },
      { type: "p", text: "Scores on this site are derived by the \`calculateQualityScore\` function in \`src/data/evidenceSchema.ts\`. The function aggregates six signals into a 0-100 score:" },
      { type: "table", rows: [["Component", "Weight", "What it measures"], ["\`evidence\`", "25%", "Share of material claims with at least one receipt"], ["\`authority\`", "20%", "Average authority of cited sources (primary = 100, secondary = 75, community = 50)"], ["\`freshness\`", "15%", "Share of receipts whose freshness date is within 30 days"], ["\`contradictionRisk\`", "15%", "Inverse of contradictions in the claim ledger"], ["\`intentSatisfaction\`", "10%", "Match between the page body and the page's declared search intent"], ["\`entityCoverage\`", "15%", "Coverage of entities referenced by the page"]] },
      { type: "p", text: "The function returns an \`overall\` score that is rounded to the nearest integer and stored on the entity profile. The function returns \`false\` for \`passesQualityGate\` until evidence coverage, source authority, and overall score all clear their declared thresholds." },
      { type: "h2", text: "What scores never mean" },
      { type: "ul", items: ["A score is **not** a verdict. A high score means the entity profile has strong evidence coverage; it does not mean the entity is \"good\" for your use case. The verdict belongs to the comparison and review pages, where evidence windows and review methodology are declared.", "A score is **not** a ranking. We do not publish score-based leaderboards except where the leaderboard is a declared methodology with declared weights.", "A score is **not** durable. Scores decay as evidence ages. A page in \`refresh_required\` shows the score with a freshness warning, not as if it were current."] },
      { type: "h2", text: "What we refuse to score" },
      { type: "p", text: "We refuse to publish numeric scores for:" },
      { type: "ul", items: ["Adoption or popularity (we have no audited measurement).", "\"Best in class\" verdicts without a declared methodology and weight set.", "Vendor trust or security certification without access to the certification document.", "User satisfaction or review scores without a verified sample and methodology.", "Latency, uptime, or cost without our own measurement or a cited primary source."] },
      { type: "p", text: "When a metric is unavailable we say so plainly. We do not synthesize a number to fill a table cell." },
      { type: "h2", text: "Declaration on every comparison page" },
      { type: "p", text: "Comparison pages declare:" },
      { type: "ul", items: ["The scoring dimensions and their weights.", "The evidence window for each product.", "Any vendor relationship that could influence the score (with reference to [](/trust/affiliate-disclosure)).", "The freshness of the underlying data."] },
      { type: "p", text: "The declaration lives in the methodology section of every comparison page and is reproduced from [](/trust/comparison-methodology)." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Source classification](/trust/source-classification)", "[Corrections](/trust/corrections)", "[Freshness policy](/trust/freshness-policy) — how rating freshness is enforced"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/data/evidenceSchema.ts\` (\`QualityScore\`, \`calculateQualityScore\`, \`passesQualityGate\`, retrieved 2026-08-22). The score calculation referenced on this page.", "Internal — \`src/content/registry/evidence-ledger.ts\` (retrieved 2026-08-22). The receipt store referenced by \`evidence\` and \`authority\` components."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "source-classification": {
    title: "Source Classification — How We Classify Evidence by Authority",
    description: "How BestAIAgent.in classifies sources: primary, secondary, and community. Definitions, examples, and how classification interacts with evidence gates.",
    blocks: [
      { type: "p", text: "Every evidence receipt carries an \`authority\` field: \`primary\`, \`secondary\`, or \`community\`. The classification determines which evidence gate the receipt satisfies and how the receipt is weighted by [](/trust/rating-methodology). This page documents how we classify each tier." },
      { type: "h2", text: "Primary" },
      { type: "p", text: "A source is \`primary\` when it originates the claim or certifies the underlying fact. Examples on this site:" },
      { type: "ul", items: ["Vendor pricing pages (e.g. \`cursor.com/pricing\`, \`anthropic.com/pricing\`).", "Vendor product / capability documentation.", "Vendor security and compliance pages.", "Official protocol specifications (e.g. \`modelcontextprotocol.io/specification\`).", "Statutes, regulations, and official government publications (e.g. the Digital Personal Data Protection Act, 2023).", "Official repositories and the files they host."] },
      { type: "p", text: "A primary source may still be wrong. We do not treat \`primary\` as proof; we treat it as the strongest class of source we can cite." },
      { type: "h2", text: "Secondary" },
      { type: "p", text: "A source is \`secondary\` when it reports on, analyses, or independently tests a primary claim. Examples on this site:" },
      { type: "ul", items: ["Reputable technology publications with editorial standards.", "Independent benchmark or testing organisations.", "Conference papers and peer-reviewed research.", "Standards bodies and their published standards."] },
      { type: "p", text: "Secondary sources are weighted below primary sources in the rating methodology and cannot alone satisfy a \`STANDARD\` gate for material claims." },
      { type: "h2", text: "Community" },
      { type: "p", text: "A source is \`community\` when it is anecdotal or crowd-supplied. Examples on this site:" },
      { type: "ul", items: ["Forum threads and discussion boards.", "Personal blog posts without editorial standards.", "Social media posts.", "Conference talks without published proceedings."] },
      { type: "p", text: "Community sources may be cited to illustrate a use case or a reported experience but cannot satisfy any evidence gate on their own. When we cite a community source we mark it as anecdotal." },
      { type: "h2", text: "Interactions with evidence gates" },
      { type: "p", text: "The \`STANDARD\`, \`COMPARISON\`, and \`CRITICAL\` gates have minimum authority requirements:" },
      { type: "ul", items: ["\`STANDARD\` requires 1+ primary source.", "\`COMPARISON\` requires 2+ primary sources (one per product side).", "\`CRITICAL\` requires 2+ primary OR 1 primary + 2 secondary."] },
      { type: "p", text: "A claim supported only by secondary or community sources is reclassified as \`unresolved\` in the claim ledger, regardless of how confident the model appears to be." },
      { type: "h2", text: "Source classification register" },
      { type: "p", text: "The canonical source classification register lives in \`src/content/registry/evidence-ledger.ts\`. Each entry carries:" },
      { type: "ul", items: ["\`url\` (canonical URL of the source)", "\`publisher\` (entity that controls the source)", "\`authority\` (\`primary\`, \`secondary\`, \`community\`)", "\`retrievedAt\` (ISO 8601 date)"] },
      { type: "p", text: "When we change a source's classification we log the change in [](/trust/corrections)." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/data/evidenceSchema.ts\` (\`EvidenceSource.authority\`, retrieved 2026-08-22). The schema definition referenced on this page.", "Internal — \`src/content/registry/evidence-ledger.ts\` (retrieved 2026-08-22). The classification register this page references."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "evidence-methodology": {
    title: "Evidence Methodology — Passage-and-Locator Discipline",
    description: "How BestAIAgent.in collects, classifies, and weighs evidence: STANDARD, COMPARISON, and CRITICAL gates, passage quotations, and freshness windows.",
    blocks: [
      { type: "p", text: "Every material factual claim on BestAIAgent.in is tied to a stored evidence receipt. This page documents the receipts, the evidence gates, and the freshness windows we apply. If a claim has no receipt, we either remove it or mark it unresolved." },
      { type: "h2", text: "What a receipt looks like" },
      { type: "p", text: "Each receipt is an \`EvidenceSource\` object with the following required fields:" },
      { type: "ul", items: ["\`url\` — the canonical URL of the source document.", "\`publisher\` — the entity that controls the source.", "\`retrievedAt\` — the ISO 8601 date the URL was fetched and the passage verified.", "\`passage\` — the exact supporting passage quoted from the source. Paraphrases are not accepted.", "\`authority\` — one of \`primary\`, \`secondary\`, or \`community\`.", "\`locator\` — optional section heading, page number, or selector that pinpoints the passage inside long-form documents.", "\`freshness\` — optional publication or last-modified date for volatile sources."] },
      { type: "p", text: "A claim references one or more receipts via \`sourceIds\`. A claim without receipts is unpublished; a claim whose receipts have aged past \`expiresAt\` is re-verified before the next refresh cycle." },
      { type: "h2", text: "What we do not use" },
      { type: "ul", items: ["We do not invent a \`contentHash\` field. Some adjacent projects use a content hash to authenticate passage quotations, but this repository's evidence schema does not include that field. SHA-256 digests in this repo are reserved for build artifact integrity (\`checksums.sha256\`) and are not used to authenticate evidence passages.", "We do not infer a quote from training data. The model that drafts the page may propose a quote, but a human reviewer must verify the quote against the fetched source before publication.", "We do not fabricate source URLs to satisfy an evidence gate. When a primary source is unavailable, the claim is either removed or reclassified as unresolved."] },
      { type: "h2", text: "Evidence gates" },
      { type: "p", text: "We apply three evidence gates, each tied to a numeric confidence threshold:" },
      { type: "table", rows: [["Gate", "Minimum confidence", "Required authority", "Use case"], ["\`STANDARD\`", "80", "1+ primary", "Material product / factual claims"], ["\`COMPARISON\`", "85", "2+ primary (one per side)", "Head-to-head comparisons"], ["\`CRITICAL\`", "90", "2+ primary, or 1 primary + 2 secondary", "Legal, medical, financial, security, regulatory, safety"]] },
      { type: "p", text: "Confidence is a derived signal, not a substitute for the authority requirement. A 99-confidence claim with no primary source fails the gate. The gate definitions live in \`src/data/evidenceSchema.ts\` under \`EVIDENCE_RULES\`." },
      { type: "h2", text: "Freshness windows" },
      { type: "p", text: "Volatile claims (price, model version, plan limits, regulatory status) carry an \`expiresAt\` date and are re-verified before publication of the next refresh cycle. Typical windows:" },
      { type: "ul", items: ["Vendor pricing: 90 days", "Regulatory status: 180 days", "Protocol revisions: 365 days", "Tool / capability lists: 60 days", "Compliance certifications: 180 days (or as soon as vendor updates the certification page)"] },
      { type: "p", text: "When a claim ages past \`expiresAt\`, the page is moved to \`refresh_required\` until re-verification completes. Pages in \`refresh_required\` are not added to fresh sitemaps or \`llms.txt\`." },
      { type: "h2", text: "Where receipts live" },
      { type: "ul", items: ["Receipt store: \`src/content/registry/evidence-ledger.ts\` — id-indexed \`EvidenceSource\` and \`EvidenceClaim\` records.", "Schema types: \`src/data/evidenceSchema.ts\` — \`EvidenceSource\`, \`EvidenceClaim\`, \`EvidenceValidation\`.", "Validation function: \`validateEvidence(claims, level)\` returns \`{ isValid, contradictions }\`."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Source classification](/trust/source-classification)", "[Freshness policy](/trust/freshness-policy)", "[Corrections](/trust/corrections)", "[Author and reviewer policy](/trust/author-reviewer-policy) — reviewer requirements", "[Privacy and DPDP editorial policy](/trust/privacy-dpdp-editorial-policy) — evidence standards for legal claims"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/data/evidenceSchema.ts\` (\`EVIDENCE_RULES\`, retrieved 2026-08-22). The schema that defines \`STANDARD\`, \`COMPARISON\`, and \`CRITICAL\` gates and their authority requirements.", "Internal — \`src/content/registry/evidence-ledger.ts\` (retrieved 2026-08-22). The canonical receipt store this page references."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "affiliate-disclosure": {
    title: "Affiliate Disclosure and Editorial Independence",
    description: "BestAIAgent.in's affiliate disclosure, commercial relationship policy, and the editorial firewall that prevents partnerships from influencing verdicts.",
    blocks: [
      { type: "p", text: "BestAIAgent.in participates in vendor affiliate programmes. This page discloses that fact, explains how affiliate relationships are walled off from editorial decisions, and tells you where to find the disclosure on each affected page." },
      { type: "h2", text: "What is an affiliate link" },
      { type: "p", text: "An affiliate link is a tracked URL that identifies the user as having arrived at a vendor from BestAIAgent.in. When the user signs up for a paid plan, the vendor pays BestAIAgent.in a commission. Affiliate commissions do not increase the price the user pays." },
      { type: "h2", text: "Where affiliate links appear" },
      { type: "p", text: "Affiliate links appear in three contexts:" },
      { type: "p", text: "1. Inside comparison and review pages, after the verdict section, as a clearly labelled \"Sign up\" or \"Try free\" call-to-action. 2. Inside entity profile pages, as a labelled action button. 3. Inside product round-ups, in the closing paragraph." },
      { type: "p", text: "The disclosure is reproduced on every page that links to a commercial partner. The disclosure reads: \"BestAIAgent.in may earn a commission when you sign up through this link.\"" },
      { type: "h2", text: "The editorial firewall" },
      { type: "p", text: "The following rules apply regardless of whether a vendor is in our affiliate programme:" },
      { type: "ul", items: ["Affiliate participation does not determine inclusion. We review products that are not in our affiliate programme and refuse to review products that are.", "Affiliate participation does not determine ranking. The verdict and ordering on every comparison page are determined by the declared methodology on that page.", "Affiliate participation does not determine verdicts. We do not soften a verdict to preserve a partnership, and we do not sharpen a verdict to disqualify a non-partner.", "Affiliate participation does not determine freshness. We re-verify claims on the same schedule regardless of whether the vendor is a partner."] },
      { type: "p", text: "When a vendor relationship changes (e.g. we join or leave a partner programme), we log the change in [](/trust/corrections)." },
      { type: "h2", text: "What we never do" },
      { type: "ul", items: ["We never mark up a page with \`Affiliate\` or commercial schema to influence search rankings.", "We never swap a verdict or a recommended plan to favour a higher-commission tier.", "We never hide the disclosure behind a fold or a tooltip. The disclosure is visible to every user."] },
      { type: "h2", text: "What we always do" },
      { type: "ul", items: ["We always declare the methodology on every comparison page (see [](/trust/comparison-methodology)).", "We always declare the evidence window on every review and pricing page (see [](/trust/evidence-methodology)).", "We always identify the reviewer on every page (see [](/trust/author-reviewer-policy))."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Author / reviewer policy](/trust/author-reviewer-policy)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — editorial independence policy (this site, retrieved 2026-08-22). The policy this page documents.", "Internal — \`src/content/registry/content-registry.ts\` (retrieved 2026-08-22). The lifecycle metadata referenced by the editorial firewall."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "freshness-policy": {
    title: "Freshness Policy — When Pages Are Re-verified",
    description: "How BestAIAgent.in declares and enforces freshness: re-verification windows, lifecycle states, and the difference between refresh and correction.",
    blocks: [
      { type: "p", text: "Every claim on BestAIAgent.in has a freshness window. When a window closes, the affected page enters a \`refresh_required\` state until the claim is re-verified. This page documents the windows we use and the page lifecycle that results." },
      { type: "h2", text: "Default windows by claim type" },
      { type: "table", rows: [["Claim type", "Window", "Rationale"], ["Vendor pricing", "90 days", "Vendor prices change without notice"], ["Model version / capability list", "60 days", "Vendors release model updates frequently"], ["Regulatory status", "180 days", "Rule changes are infrequent but consequential"], ["Protocol revision", "365 days", "Specifications change slowly"], ["Compliance certification", "180 days", "Certifications expire or are renewed annually"], ["Methodology (this page and siblings)", "180 days", "Policy is reviewed semi-annually"]] },
      { type: "h2", text: "Lifecycle states affected by freshness" },
      { type: "p", text: "The content lifecycle is defined in \`src/content/registry/content-registry.ts\`:" },
      { type: "ul", items: ["\`published\` — current and indexable.", "\`monitored\` — current but flagged for the next scheduled refresh.", "\`refresh_required\` — a receipt has aged past \`expiresAt\`; the page is removed from fresh sitemaps and \`llms.txt\` until re-verification completes.", "\`rejected\` — the page can no longer be supported and is removed from indexable surfaces."] },
      { type: "p", text: "A page in \`refresh_required\` may still be served to users (with a \"This page is being re-verified\" notice) but it does not appear in the discovery surfaces of this site until the page is back in \`published\`." },
      { type: "h2", text: "How freshness is enforced" },
      { type: "ul", items: ["Every claim in \`src/content/registry/evidence-ledger.ts\` carries an optional \`expiresAt\` date.", "A scheduled job queries the ledger for expired claims and moves the owning pages to \`monitored\` 30 days before expiry, then to \`refresh_required\` on the expiry date.", "Re-verification requires a fresh \`retrievedAt\` date and a fresh passage quotation from the cited source.", "Re-verified claims enter the ledger with the same id but updated \`verifiedAt\`, \`retrievedAt\`, and (optionally) \`expiresAt\`."] },
      { type: "h2", text: "What we never do" },
      { type: "ul", items: ["We never silently update a page's \"Last reviewed\" date. The date reflects the last genuine review, not the build timestamp.", "We never publish a page with a fake freshness window. The window is declared in the frontmatter and enforced by the schema.", "We never back-date a verification to preserve an old receipt's apparent freshness."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Corrections](/trust/corrections)", "[Author and reviewer policy](/trust/author-reviewer-policy) — who reviews each refresh cycle"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/content/registry/evidence-ledger.ts\` (\`EvidenceClaim.expiresAt\`, retrieved 2026-08-22). The expiry field that drives freshness transitions.", "Internal — \`src/content/registry/content-registry.ts\` (\`lifecycleStatus\`, retrieved 2026-08-22). The lifecycle state machine referenced by this policy."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "privacy-dpdp-editorial-policy": {
    title: "Privacy and DPDP Editorial Policy",
    description: "BestAIAgent.in's editorial policy on India privacy law, the Digital Personal Data Protection Act 2023, and how compliance claims are evidenced on this site.",
    blocks: [
      { type: "p", text: "Pages on BestAIAgent.in that touch on Indian data protection law, GST, cross-border data transfer, or India-region product availability must satisfy the \`CRITICAL\` evidence gate. This page documents the editorial rules we apply to those pages." },
      { type: "h2", text: "What the CRITICAL gate requires" },
      { type: "p", text: "For any claim about Indian law, regulation, certification, or compliance, the claim must cite:" },
      { type: "ul", items: ["The statute or regulation (e.g. the Digital Personal Data Protection Act, 2023).", "An official government source where available (e.g. MeitY for DPDP, the GST Council for tax rates).", "Where the law is in force, the date the relevant section came into force.", "Where the law is not yet in force, the date the implementing rules were notified."] },
      { type: "p", text: "We do not paraphrase a statute. The receipt includes the exact passage and the section / schedule locator." },
      { type: "h2", text: "What we refuse to claim" },
      { type: "ul", items: ["We do not state that a product \"is DPDP-compliant\" without a primary source (vendor privacy policy, audit report, or certification) that supports the claim. Vendor marketing language is not sufficient.", "We do not state a universal breach notification deadline. The DPDP Act and its draft rules specify timelines that depend on the nature of the breach and the responsible party's classification. We cite the specific rule rather than assert a single number.", "We do not state a universal penalty. The Act specifies penalty ranges that depend on the nature of the violation. We cite the section and the range.", "We do not state a universal \"data principal right\" — the rights depend on the lawful basis for processing and on the data fiduciary's classification.", "We do not state that a vendor \"stores data in India\" without a primary source. Vendor data-residency claims are re-verified at the freshness window declared on [](/trust/freshness-policy)."] },
      { type: "h2", text: "What we do claim" },
      { type: "ul", items: ["We state the existence and effective date of the Digital Personal Data Protection Act, 2023, with a primary source citation.", "We state the GST rate applicable to software / IT services in India, with a primary source citation to the GST Council Rate Schedule.", "We summarise data principal rights at a high level, with citations to the relevant sections of the Act.", "We summarise consent requirements at a high level, with citations to the relevant sections of the Act."] },
      { type: "p", text: "When a page requires more specific advice (e.g. \"what should my company do?\"), the page links to a qualified legal practitioner rather than answering the question itself." },
      { type: "h2", text: "Effective dates we publish" },
      { type: "table", rows: [["Item", "Effective date", "Source"], ["Digital Personal Data Protection Act, 2023 receives Presidential assent", "11 August 2023", "Gazette of India, Act No. 22 of 2023 — bound to \`claim:dpdp-act-existence\`"], ["GST at 18% on software / IT services", "Per current GST Council Rate Schedule", "GST Council Rate Schedule — bound to \`claim:gst-18-software\`"]] },
      { type: "h2", text: "When the rules change" },
      { type: "p", text: "When a statute, regulation, or rule referenced on this site is amended, we:" },
      { type: "ul", items: ["Update the affected claim in the evidence ledger with a fresh \`retrievedAt\` date.", "Log the change in [](/trust/corrections).", "Re-verify every affected page on the next refresh cycle."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Source classification](/trust/source-classification)", "[Corrections](/trust/corrections)", "[Freshness policy](/trust/freshness-policy)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Government of India — Digital Personal Data Protection Act, 2023 (primary, retrieved 2026-08-22). Cited as the source for the Act's existence, assent date, and the section references on this site.", "GST Council — Rate Schedule (primary, retrieved 2026-08-22). Cited as the source for the 18% GST rate referenced on India pricing pages."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2026-11-22 (volatile claim window)", "Reviewer: BestAIAgent.in editorial board, with legal review by an Indian-qualified practitioner (consultation scheduled)"] },
    ]
  },
  "editorial-methodology": {
    title: "Editorial Methodology — How BestAIAgent.in Reviews, Scores, and Publishes",
    description: "How BestAIAgent.in authors, reviews, and publishes AI agent content: editorial independence, source hierarchy, corrections, and author identification.",
    blocks: [
      { type: "p", text: "BestAIAgent.in publishes entity and topic authority content about AI agents for Indian developers, startups, enterprises, and regulated organizations. This page documents how we decide what to publish, what we refuse to publish, who is responsible for each page, and how we correct mistakes." },
      { type: "h2", text: "What this page covers" },
      { type: "ul", items: ["Editorial independence and affiliate disclosure", "Source hierarchy and authority classification", "Page classes and their review requirements", "Author and reviewer identification policy", "Corrections and version history", "When we will not publish a page"] },
      { type: "h2", text: "Editorial independence" },
      { type: "p", text: "BestAIAgent.in is editorially independent. Vendor relationships, affiliate programs, and commercial partnerships do not determine which products we cover, the order in which we cover them, the verdicts we reach, or the framing of any review. Affiliate disclosure is published at [](/trust/affiliate-disclosure) and on every page that links to a commercial partner." },
      { type: "p", text: "We pay for our own product evaluations whenever feasible. Where a vendor provides a temporary licence for testing, we disclose that fact on the affected review page in the \"How we tested\" section." },
      { type: "h2", text: "Source hierarchy" },
      { type: "p", text: "We classify sources by authority before assigning evidence class:" },
      { type: "table", rows: [["Class", "Definition", "Examples"], ["**Primary**", "Vendor / official / statutory source that originates the claim", "Vendor pricing pages, official protocol specifications, statutes, official repositories"], ["**Secondary**", "Independent reporting, peer-reviewed research, official testing bodies", "Reputable technology publications, standards bodies, conference papers"], ["**Community**", "Anecdotal or community-supplied", "Forum threads, blog posts, conference talks without published proceedings"]] },
      { type: "p", text: "For any material claim about price, capability, compliance, or compatibility we require at least one primary source. Comparison pages require equivalent primary sources for both products under review. Legal, medical, financial, and security claims require multiple authoritative sources plus human review — see [](/trust/comparison-methodology) and the relevant methodology pages." },
      { type: "h2", text: "Page classes and review requirements" },
      { type: "p", text: "We use the following page classes. The review depth depends on the risk of the claim being wrong." },
      { type: "ul", items: ["**Pillar** — synthesizes a domain. Requires primary-source evidence for every material claim and editorial review before publication.", "**Cluster** — addresses a specific question inside a pillar. Requires primary-source evidence and editorial review.", "**Comparison** — head-to-head product review. Requires equivalent evidence windows for both products. See [](/trust/comparison-methodology).", "**Review** — single-product review. Requires a tested or desk-researched evaluation method declared up front.", "**Pricing** — current vendor pricing. Requires primary-source evidence and a freshness window. See [](/trust/freshness-policy).", "**Methodology** — this page and its siblings. Reviewed before publication and re-reviewed when underlying policy changes."] },
      { type: "h2", text: "Author and reviewer identification" },
      { type: "p", text: "Every published page identifies the author (where named) and the reviewer (always named). We publish corrections when material errors are identified, even if the page has aged off the homepage. The corrections log lives at [](/trust/corrections)." },
      { type: "h2", text: "When we will not publish a page" },
      { type: "p", text: "We refuse to publish pages when:" },
      { type: "ul", items: ["The page exists primarily to rank for a keyword rather than answer a real user question.", "The required evidence is not available from a primary source.", "The vendor refuses to confirm or deny a claim that materially affects the user's decision.", "The page duplicates an existing page with only reordered adjectives.", "The page would require us to certify a vendor's compliance or security without access to verifiable evidence."] },
      { type: "p", text: "We quarantine such pages as \`quarantined_template\` rather than delete them, so the candidate inventory is auditable." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Source classification](/trust/source-classification)", "[Corrections and version history](/trust/corrections)", "[Freshness policy](/trust/freshness-policy)", "[Affiliate disclosure](/trust/affiliate-disclosure)", "[Author / reviewer policy](/trust/author-reviewer-policy)", "[Privacy and DPDP editorial policy](/trust/privacy-dpdp-editorial-policy)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Anthropic — Claude's Constitution (primary, retrieved 2026-08-22). Cited for the principle that model behaviour is constrained by documented principles rather than inferred.", "OpenAI — Function Calling documentation (primary, retrieved 2026-08-22). Cited as the source for the tool-calling model used across this site.", "Internal editorial charter — this site."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "corrections": {
    title: "Corrections and Version History",
    description: "How BestAIAgent.in records content corrections: correction log, severity classes, retraction policy, and the difference between refresh and correction.",
    blocks: [
      { type: "p", text: "Mistakes happen. The integrity of this site depends on how we record and correct them. This page documents the correction log format, severity classes, and the difference between a correction, a refresh, and a retraction." },
      { type: "h2", text: "What a correction is" },
      { type: "p", text: "A correction is a published change to a claim that was incorrect when published. Corrections are surfaced on the affected page with a visible \"Correction\" note that links to the entry in this log." },
      { type: "p", text: "A correction is not the same as:" },
      { type: "ul", items: ["**Refresh** — re-verifying claims whose evidence aged past \`expiresAt\`. The claim may still be correct; we are checking.", "**Update** — expanding the page with new evidence or context.", "**Retraction** — withdrawing a page entirely because its central claim cannot be supported."] },
      { type: "h2", text: "Severity classes" },
      { type: "p", text: "We use three severity classes for corrections:" },
      { type: "table", rows: [["Class", "When", "Page treatment"], ["**Minor**", "Typographical error, broken link, formatting issue", "In-page note, log entry"], ["**Material**", "A claim was wrong or out of date but the page's overall conclusion holds", "In-page banner, log entry, optional \`lastReviewed\` reset"], ["**Substantive**", "The page's conclusion no longer holds, or the page is unsafe to use", "Page moves to \`refresh_required\` or \`rejected\`, retraction notice on the index"]] },
      { type: "h2", text: "Correction log format" },
      { type: "p", text: "Each entry in this log includes:" },
      { type: "ul", items: ["Affected page slug", "Date of correction", "Severity class", "Brief description of the change", "Receipt that prompted the correction", "Reviewer name"] },
      { type: "h2", text: "Current correction log" },
      { type: "table", rows: [["Date", "Page", "Severity", "Description", "Receipt"], ["2026-08-22", "Multiple", "—", "Initial publication of the corrections log", "Internal — \`src/content/registry/content-registry.ts\`"]] },
      { type: "p", text: "We have no prior corrections to report. New corrections will be appended below this line." },
      { type: "h2", text: "How to report a suspected error" },
      { type: "p", text: "Send corrections, supporting evidence, and the URL of the affected page to the address listed on [](/about). We aim to triage submissions within 7 calendar days and to publish either a correction entry or a written explanation of why we declined to correct." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Source classification](/trust/source-classification)", "[Author / reviewer policy](/trust/author-reviewer-policy)", "[Freshness policy](/trust/freshness-policy)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`src/content/registry/content-registry.ts\` (\`lifecycleStatus\` field, retrieved 2026-08-22). The lifecycle state machine that drives the \`refresh_required\` and \`rejected\` transitions referenced in this page.", "Internal — \`src/content/registry/evidence-ledger.ts\` (\`EvidenceClaim.status\` field, retrieved 2026-08-22). The claim status (\`active\`, \`expired\`, \`contradicted\`, \`superseded\`) that distinguishes a correction from a refresh."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
  "author-reviewer-policy": {
    title: "Author and Reviewer Identification Policy",
    description: "How BestAIAgent.in identifies authors and reviewers on every published page, including pseudonymous authorship rules and reviewer requirements.",
    blocks: [
      { type: "p", text: "Every published page on BestAIAgent.in identifies an author (where named) and a reviewer (always named). This page documents the rules we apply." },
      { type: "h2", text: "What we publish on every page" },
      { type: "p", text: "Every published page includes:" },
      { type: "ul", items: ["**Author** — the writer's name, or \"BestAIAgent.in editorial team\" for unattributed pieces.", "**Reviewer** — the named reviewer who checked the page against [](/trust/editorial-methodology).", "**Last reviewed** — the ISO 8601 date the page was last reviewed for accuracy.", "**Next scheduled review** — the ISO 8601 date the next review is due."] },
      { type: "p", text: "The author and reviewer are recorded in the page frontmatter under \`author\`, \`reviewer\`, \`lastReviewed\`, and \`nextReviewDue\`." },
      { type: "h2", text: "Author identification rules" },
      { type: "ul", items: ["Authors who write under their real name must have a public bio on this site linking to their other work. Pseudonymous authors are permitted for personal-safety reasons but must be approved by the editorial board.", "Authors are responsible for the prose, the structure, and the accuracy of the claims they attribute to other people.", "Authors may not review their own pages. The reviewer is always a different person."] },
      { type: "h2", text: "Reviewer requirements" },
      { type: "p", text: "The reviewer:" },
      { type: "ul", items: ["Checks the page against [](/trust/editorial-methodology).", "Verifies that every material claim has a receipt in \`src/content/registry/evidence-ledger.ts\`.", "Verifies that no claim contradicts an existing receipt.", "Confirms that the methodology declared on the page matches the rules in [](/trust/comparison-methodology) or [](/trust/rating-methodology) where applicable.", "Adds their name to the page frontmatter before publication."] },
      { type: "p", text: "The reviewer is the editorial board for methodology pages and a domain specialist (or the editorial board if no specialist is available) for product pages." },
      { type: "h2", text: "When the reviewer is the editorial board" },
      { type: "p", text: "For methodology pages and pages with no product claim, the reviewer is the BestAIAgent.in editorial board. The board is identified on [](/about) and its decisions are public." },
      { type: "h2", text: "Why authorship and review are non-negotiable" },
      { type: "p", text: "Editorial transparency is not a stylistic preference; it is the foundation of trust on a research site. Three reasons we treat author and reviewer identification as mandatory:" },
      { type: "p", text: "1. **Accountability.** A named reviewer can be asked to defend a decision. An anonymous page cannot be held to account. 2. **Calibration.** Future reviewers can compare their verdict against prior reviewer decisions and identify drift. 3. **Audit.** When a correction is filed in [](/trust/corrections), the author and reviewer at the time of publication are recorded, so the chain of responsibility is recoverable." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — [Editorial methodology](/trust/editorial-methodology) (this site, retrieved 2026-08-22). The policy this page extends."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-22", "Next scheduled review: 2027-02-22", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },

  "how-to-verify": {
    title: "How to Verify a Claim on BestAIAgent.in",
    description: "A practical, step-by-step guide to checking any claim on this site yourself, rather than taking a published field at face value.",
    blocks: [
      { type: "p", text: "Every other trust page on this site documents how we produce and gate content. This page is different: it's a walkthrough for you, the reader, on how to independently check whether a specific claim on a specific page actually holds up — in under a minute, using nothing but the page itself and its cited source." },
      { type: "h2", text: "Step 1: Find the receipt, not just the claim" },
      { type: "p", text: "On an entity page (an agent, model, framework or provider), look for the evidence block near the claim — it names a publisher, a retrieval date, and links to a primary source. If a field has no such block, it means the field is unknown by this site's own rule, not that the claim is unverified-but-true — treat it as genuinely unknown." },
      { type: "h2", text: "Step 2: Open the primary source directly" },
      { type: "p", text: "Click through to the linked source and read the passage yourself, rather than trusting our paraphrase of it. This matters most for anything volatile — price, plan limits, model version — since these can change after our retrieval date." },
      { type: "h2", text: "Step 3: Check the retrieval date against how fast the fact moves" },
      { type: "p", text: "A pricing fact retrieved 90 days ago is a different risk than an identity fact retrieved 90 days ago — see [](/trust/freshness-policy) for the specific re-verification windows we apply per claim type. If a page looks stale for its claim type, that's worth flagging as a correction rather than assuming it still holds." },
      { type: "h2", text: "Step 4: Distinguish a fact from an editorial judgment" },
      { type: "p", text: "A number with a citation is a fact. A recommendation, a \"best for X\" framing, or a comparative verdict is an editorial judgment built on top of facts — it should be labeled as such on the page. If a judgment reads like a fact with no methodology attached, that's a real defect worth reporting." },
      { type: "h2", text: "Step 5: Report what doesn't hold up" },
      { type: "p", text: "If a source doesn't say what the page claims it says, or the retrieval date is older than the freshness window for that claim type, use [](/trust/corrections) to report it with the specific field and the source you checked. This is the same reporting path a reviewer would use internally." },
      { type: "h2", text: "What verification does not mean" },
      { type: "ul", items: ["A verified identity does not mean every field on that entity's page is verified — verification is field-level, not whole-page.", "A primary source can still be wrong; verification confirms we cited it accurately, not that the source itself is infallible.", "An evidence-ready comparison does not mean a universal winner — see [](/trust/comparison-methodology) for what a comparison page does and doesn't assert."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Source classification](/trust/source-classification)", "[Freshness policy](/trust/freshness-policy)", "[Corrections](/trust/corrections)", "[Rating methodology](/trust/rating-methodology)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — [Evidence methodology](/trust/evidence-methodology) (this site, retrieved 2026-08-29). The receipt structure this page teaches readers to check."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-29", "Next scheduled review: 2027-02-28", "Reviewer: BestAIAgent.in editorial board"] },
    ]
  },
};
