import type { ContentBlock } from "@/components/ContentBlocks";

export type TrustPage = { title: string; description: string; blocks: ContentBlock[] };

export const trustPages: Record<string, TrustPage> = {
  "comparison-methodology": {
    title: "Comparison Methodology — How Comparison Pages Are Built",
    description: "How BestAIAgent.in builds comparison pages: the evidence-ready gate, what a comparison page does and doesn't assert, and how duplicate-direction URLs are handled.",
    blocks: [
      { type: "p", text: "Comparison pages are easy to misuse — a \"vs\" page invites a verdict even when the underlying evidence doesn't support one. This page documents the actual gate a comparison must clear to be indexed, and what it never claims." },
      { type: "h2", text: "The evidence-ready gate" },
      { type: "p", text: "A comparison is defined in code as two entity references, a title, a status (\`evidence-ready\` or \`refreshing\`), and a list of editorial notes. It becomes publicly indexable only when both referenced entities independently resolve as verified, public entities — meaning each has \`verification: \"verified\"\` and at least one evidence record whose \`status\` is \`verified\`, \`authority\` is \`primary\`, and \`contentHash\` matches the \`sha256:[0-9a-f]{64}\` format. This check is a function, not a manual judgment call, and it's re-run against the current data every time the site builds." },
      { type: "p", text: "If either side isn't yet verified, the comparison stays at status \`refreshing\`: the page is still reachable at its URL, but it's excluded from the sitemap and \`llms.txt\`, and its detail page is marked \`noindex\`." },
      { type: "h2", text: "What a comparison page asserts, and what it doesn't" },
      { type: "ul", items: ["It asserts that both entities' identities are independently verified against a primary source — nothing more.", "It does not assert a winner. The notes field is free-form editorial text describing what's genuinely known and unknown about each side; it is never a numeric score or a ranked verdict.", "It does not inherit pricing, benchmark, or capability claims from the identity check. Those remain unknown unless separately evidenced on the entity's own page."] },
      { type: "h2", text: "Duplicate-direction URLs" },
      { type: "p", text: "When both an \"A vs. B\" and a \"B vs. A\" URL exist for the same pair, the non-canonical direction is a permanent redirect to the canonical one. These redirects are declared in the same registry used for every other legacy URL on this site — \`data/legacy-redirects.json\`, consumed by \`next.config.ts\`'s \`redirects()\` — not a separate comparison-specific system." },
      { type: "h2", text: "A bug this exact check has caught" },
      { type: "p", text: "This isn't hypothetical: a comparison titled \"Cursor vs GitHub Copilot\" once had its \`a\`/\`b\` fields quietly pointing at two unrelated entities from an earlier URL migration. Nothing in the type system catches a title that doesn't match its own data — that has to be checked by eye when a comparison is added or reviewed. See \`CONTRIBUTING.md\` for the same example." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Source classification](/trust/source-classification)", "[How to verify a claim](/trust/how-to-verify)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/catalog.ts\` (\`isPublicIndexableComparison\`, \`publicIndexableComparisons\`). The actual gate function this page describes.", "Internal — \`lib/comparisons.ts\` (\`Comparison\` type and the \`comparisons\` array). The data structure this page describes.", "Internal — \`data/legacy-redirects.json\` and \`next.config.ts\`. The real redirect registry referenced above."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "rating-methodology": {
    title: "Rating Methodology — Why This Site Doesn't Publish Numeric Scores",
    description: "BestAIAgent.in does not compute or publish a numeric quality or capability score for any entity. This page explains why, and what's shown instead.",
    blocks: [
      { type: "p", text: "This page exists mainly to say plainly what this site does not do: BestAIAgent.in does not compute, store, or display a numeric score — not an overall quality score, not a per-dimension score, not a composite ranking — for any agent, model, framework, or provider. There is no scoring function anywhere in this codebase." },
      { type: "h2", text: "Why no numeric scores" },
      { type: "p", text: "A numeric score creates an appearance of precision that the underlying evidence usually can't support. Whether an entity is a good fit for a specific task depends on requirements a static score can't encode — deployment constraints, pricing at your actual usage volume, compliance needs, language support. Presenting that as one number would trade honesty for a false sense of comparability. Earlier versions of this site did publish composite scores; that system was retired, and this page's job is to make sure that decision doesn't quietly drift back in through new content." },
      { type: "h2", text: "What's shown instead" },
      { type: "ul", items: ["**Verification status** — whether an entity's identity has cleared the evidence gate (\`verified\`), is only source-linked, or remains \`pending\`/\`unknown\`. This is a binary identity check, not a quality judgment.", "**Evidence receipts** — the specific primary source, retrieval date, and content hash behind each verified fact, so you can check it yourself rather than trust a summary.", "**Dated facts** — specific fields (pricing, categories) that carry their own source and date, shown as facts, not folded into a composite number.", "**Selection frameworks** — pages like [](/best-ai-agents) describe what to check for a given use case (e.g. latency for voice agents, license for self-hosting) without collapsing those criteria into one ranking."] },
      { type: "h2", text: "What we refuse to publish" },
      { type: "p", text: "Consistent with not scoring, this site does not publish:" },
      { type: "ul", items: ["\`AggregateRating\`, \`Review\`, or review-count structured data unless a page has genuine, checkable review data behind it (currently: none does).", "Adoption or popularity figures without an audited source.", "\"Best in class\" superlatives without the specific criteria and evidence spelled out on the same page.", "Latency, uptime, or cost figures without our own reproducible measurement or a cited primary source."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Source classification](/trust/source-classification)", "[Editorial methodology](/trust/editorial-methodology)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/catalog-types.ts\` and \`lib/catalog.ts\`. The real \`Entity\`/\`EvidenceRecord\` types and \`isEntityIndexable\` gate — neither includes a score field.", "Internal — \`README.md\`, \"What's deliberately excluded\" section. States the no-synthetic-rankings principle this page documents."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "source-classification": {
    title: "Source Classification — Primary and Secondary Evidence",
    description: "How BestAIAgent.in classifies evidence sources: the two real authority tiers, what each requires, and how classification gates publication.",
    blocks: [
      { type: "p", text: "Every evidence record on this site carries an \`authority\` field with exactly two possible values: \`primary\` or \`secondary\`. This page documents what each means and how it affects whether an entity or comparison can be publicly indexed." },
      { type: "h2", text: "Primary" },
      { type: "p", text: "A source is \`primary\` when it originates from the entity's own official channel: its GitHub/GitLab repository (via the official API), its own model card, its own documentation, or its own official site. Examples already in this catalog: \`api.github.com/repos/...\` for repository identity, \`huggingface.co/api/models/...\` for model cards, a vendor's own pricing or feature page." },
      { type: "p", text: "Only \`primary\`-authority evidence with a \`verified\` status and a validly-formatted content hash counts toward the publication gate (\`isEntityIndexable\`). A primary source can still turn out to be wrong or outdated — \`primary\` describes where the claim came from, not a guarantee of permanent accuracy." },
      { type: "h2", text: "Secondary" },
      { type: "p", text: "A source is \`secondary\` when it reports on or analyzes an entity rather than originating from the entity itself — independent reporting, third-party benchmarks, or community-maintained documentation. Secondary evidence is recorded in the same \`EvidenceRecord\` shape but does not, on its own, satisfy the publication gate for verified status." },
      { type: "h2", text: "There is no third tier" },
      { type: "p", text: "Some earlier drafts on this site described a third \`community\` tier (forum posts, social media). That tier was never implemented — the real \`EvidenceAuthority\` type in \`lib/catalog-types.ts\` only defines \`\"primary\" | \"secondary\"\`. Anecdotal sources aren't a recognized evidence class on this site at all; they're simply not evidence." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/catalog-types.ts\` (\`EvidenceAuthority\`, \`EvidenceRecord\`). The real type definitions this page describes.", "Internal — \`lib/catalog.ts\` (\`isEvidenceVerified\`). The function that requires \`authority === \"primary\"\` for verified status."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "evidence-methodology": {
    title: "Evidence Methodology — What a Receipt Actually Contains",
    description: "How BestAIAgent.in records evidence: the real EvidenceRecord fields, the verification check, and the difference between a verified identity and a verified capability claim.",
    blocks: [
      { type: "p", text: "Every verified entity on this site has at least one evidence record backing its identity. This page documents exactly what that record contains and how it's checked — matching the real code in \`lib/catalog-types.ts\` and \`lib/catalog.ts\`, not an idealized version of it." },
      { type: "h2", text: "What an evidence record contains" },
      { type: "p", text: "Each \`EvidenceRecord\` has these fields:" },
      { type: "ul", items: ["\`sourceUrl\` — the exact API or page URL fetched (e.g. \`api.github.com/repos/OWNER/REPO\`).", "\`sourceType\` — one of \`official-repository-api\`, \`official-model-card\`, \`official-documentation\`, or \`official-site\`.", "\`publisher\` — who controls the source (e.g. \"GitHub\", \"Hugging Face\", the vendor itself).", "\`authority\` — \`primary\` or \`secondary\` (see [](/trust/source-classification)).", "\`retrievedAt\` — the ISO 8601 timestamp the source was actually fetched.", "\`contentHash\` — a \`sha256:\` hash of a canonical JSON snapshot of the specific fields checked (for a GitHub repo: id, full name, default branch, archived status, visibility, size).", "\`snapshot\` — the canonical object that was hashed, stored alongside the hash so it's inspectable.", "\`status\` — \`verified\`, \`pending\`, \`stale\`, or \`rejected\`."] },
      { type: "h2", text: "What counts as verified" },
      { type: "p", text: "\`isEvidenceVerified(record)\` requires all of: \`status === \"verified\"\`, \`authority === \"primary\"\`, a non-empty \`retrievedAt\`, and a \`contentHash\` matching \`/^sha256:[0-9a-f]{64}$/\`. An entity is publicly indexable only when its own \`verification\` field is \`\"verified\"\` **and** at least one of its evidence records passes that check." },
      { type: "h2", text: "An important limit: the hash format check is not a re-verification" },
      { type: "p", text: "The regex check confirms a hash is *shaped* like a real SHA-256 digest — it does not recompute the hash from the source and compare. That means the gate trusts whoever added the record to have actually fetched the source and hashed it honestly. This project has caught its own mistake here before: hand-typing an evidence record from memory instead of copying a script-generated one produced a syntactically valid but factually wrong hash. \`CONTRIBUTING.md\` documents this as a specific thing to check for in review." },
      { type: "h2", text: "What a verified identity does not cover" },
      { type: "p", text: "Verifying that a repository or model card exists, is public, and matches a specific name confirms *identity* — not pricing, capability, security posture, or benchmark performance. Those are separate claims that need their own evidence, and stay labeled unknown until they have it." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Source classification](/trust/source-classification)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[How to verify a claim](/trust/how-to-verify)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/catalog-types.ts\` (\`EvidenceRecord\`, \`Entity\`). The real types this page describes field-for-field.", "Internal — \`lib/catalog.ts\` (\`isEvidenceVerified\`, \`isEntityIndexable\`). The real gate functions.", "Internal — \`CONTRIBUTING.md\`. Documents the hand-typed-hash mistake referenced above as a real incident from this project's own history."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "affiliate-disclosure": {
    title: "Affiliate Disclosure",
    description: "BestAIAgent.in's current affiliate relationships: none. What would change, and what wouldn't, if that becomes untrue.",
    blocks: [
      { type: "p", text: "BestAIAgent.in does not currently participate in any vendor affiliate or commission program. There are no tracked links on this site and no revenue tied to which products appear, how they're ordered, or what a comparison page concludes." },
      { type: "h2", text: "If that changes" },
      { type: "p", text: "If an affiliate relationship is ever introduced, it will be disclosed directly on every page carrying such a link, and the following rule holds regardless: an affiliate relationship may not change an entity's verification status, an evidence record's outcome, or a comparison's evidence-ready status. Those are computed by the same gate functions described in [](/trust/evidence-methodology) and [](/trust/comparison-methodology), which have no concept of a commercial relationship as an input." },
      { type: "h2", text: "Why this page is short" },
      { type: "p", text: "This page used to describe an operating affiliate program — specific commission mechanics, disclosure placements, an editorial firewall protecting against it — none of which exists. Describing policy for a program that isn't running is exactly the kind of unsupported claim this site's own evidence standard rules out elsewhere; this page now says only what's actually true." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Comparison methodology](/trust/comparison-methodology)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/legacy.ts\` (\`affiliate-disclosure\` entry). This site's other, shorter affiliate-disclosure page states the same real policy; this page previously contradicted it."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "freshness-policy": {
    title: "Freshness Policy — What's Automated and What Isn't",
    description: "How dated fields on BestAIAgent.in are actually kept current: a manual editorial practice, not an automated re-verification pipeline.",
    blocks: [
      { type: "p", text: "Evidence records carry a \`retrievedAt\` date and authority pages carry a \`lastReviewed\` date. This page is honest about what those dates mean: there is no automated job on this site that re-fetches sources, checks for staleness, or moves pages between lifecycle states. Freshness here is a manual editorial practice, not infrastructure." },
      { type: "h2", text: "What the dates actually tell you" },
      { type: "ul", items: ["An evidence record's \`retrievedAt\` is the date that specific source was fetched and hashed. It does not update itself — it changes only when someone re-verifies and re-hashes the source.", "An authority page's \`lastReviewed\` is the date someone last checked that page's content. Pages with an old date have not necessarily gone stale, but they also haven't been re-checked recently — read the date as information, not as a freshness guarantee."] },
      { type: "h2", text: "Why this matters more for volatile fields" },
      { type: "p", text: "A pricing figure retrieved 90 days ago carries more real risk of being wrong than an identity fact retrieved 90 days ago, since prices change far more often than whether a repository exists. See [](/trust/how-to-verify) for how to check a specific claim's currency yourself rather than relying on the presence of a date alone." },
      { type: "h2", text: "What we don't claim" },
      { type: "p", text: "We don't claim a scheduled re-verification cadence, an automated expiry mechanism, or lifecycle states like \`monitored\` or \`refresh_required\` — none of that is built. If and when automated re-verification is built, this page will describe the real mechanism, not before." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[How to verify a claim](/trust/how-to-verify)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/evidence.ts\`, \`lib/authority-evidence.ts\`. The real \`retrievedAt\` fields this page describes.", "Internal — \`lib/authority-pages.ts\` (\`lastReviewed\` field on the real \`AuthorityPage\` type)."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "privacy-dpdp-editorial-policy": {
    title: "Privacy and DPDP Editorial Policy",
    description: "BestAIAgent.in's approach to claims about Indian data protection law: cite the primary source directly, never assert a compliance status without one.",
    blocks: [
      { type: "p", text: "Pages that touch Indian data protection law, GST, cross-border data transfer, or India-region availability get the same treatment as every other factual claim on this site: a real primary source, or the field stays unknown. There is no separate automated \"legal gate\" distinct from the ordinary evidence pipeline described in [](/trust/evidence-methodology) — the difference is editorial care, not different code." },
      { type: "h2", text: "What we won't claim without a source" },
      { type: "ul", items: ["That a product \"is DPDP-compliant\" — vendor marketing language alone is not sufficient; this needs a vendor privacy policy, audit report, or certification that actually supports the specific claim.", "A single universal breach-notification deadline or penalty figure — the Digital Personal Data Protection Act, 2023 and its rules specify ranges and conditions, not one number, so we cite the specific provision rather than flatten it.", "That a vendor \"stores data in India\" without the vendor's own data-residency documentation to back it."] },
      { type: "h2", text: "What we do state" },
      { type: "p", text: "The existence and passage of the Digital Personal Data Protection Act, 2023 (assented to by the President on 11 August 2023), and general summaries of its provisions, cited to the Act itself or an official government source (e.g. MeitY). For anything more specific than a general summary — \"what should my company do\" — the honest answer is to consult a qualified legal practitioner, not this site." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Source classification](/trust/source-classification)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Government of India — Digital Personal Data Protection Act, 2023. Cited for the Act's existence and assent date."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "editorial-methodology": {
    title: "Editorial Methodology — How Content Gets Published Here",
    description: "How BestAIAgent.in actually decides what to publish: the real two-tier verification model, what editorial pages are held to, and what gets rejected.",
    blocks: [
      { type: "p", text: "This page documents the actual publication process on this site, matching \`CONTRIBUTING.md\` and the real code in \`lib/catalog.ts\` rather than an aspirational editorial-board process that was never built." },
      { type: "h2", text: "Two tiers, not a review board" },
      { type: "p", text: "Every entity starts in a legacy/imported pool with just a name and a source link — reachable, but \`noindex\`. It's promoted to a verified, indexable entity only by adding a real \`Entity\` record plus a matching \`EvidenceRecord\` built from an actual API fetch (see [](/trust/evidence-methodology)). There's no separate named-reviewer sign-off step distinct from that promotion — the evidence record itself is the review artifact, and anyone can check it by re-fetching the cited source." },
      { type: "h2", text: "What editorial (non-entity) content is held to" },
      { type: "p", text: "Authority pages, glossary entries, and guides don't go through the entity evidence gate — they're editorial by default. What is checked:" },
      { type: "ul", items: ["No fabricated statistics, ratings, or \"trusted by\" claims. If a number isn't sourced, the plain-language version is used instead of inventing one.", "No compliance or certification claims about a named company without a real source (see [](/trust/privacy-dpdp-editorial-policy) for the sharpest version of this rule).", "Internal links actually resolve — checked with a real grep-based script before merging a batch of new pages, documented in \`CONTRIBUTING.md\`.", "No mass-generated, name-swapped pages published purely to rank for a keyword variant."] },
      { type: "h2", text: "What we refuse to publish" },
      { type: "p", text: "Entities without a real, checkable evidence receipt stay in the noindex tier — no exceptions for coverage or completeness. Comparisons whose title doesn't match what their \`a\`/\`b\` fields actually point to don't ship (see [](/trust/comparison-methodology) for the real incident that taught us to check this). Schema.org blocks asserting something the page doesn't actually show — fabricated \`AggregateRating\`, invented \`offers.price\` — are rejected in review." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Rating methodology](/trust/rating-methodology)", "[Comparison methodology](/trust/comparison-methodology)", "[Source classification](/trust/source-classification)", "[Corrections](/trust/corrections)", "[Affiliate disclosure](/trust/affiliate-disclosure)", "[Author attribution](/trust/author-reviewer-policy)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`CONTRIBUTING.md\`. Documents the real two-tier model, the promotion workflow, and the specific mistakes (hand-typed hashes, mismatched comparison titles) this policy is designed to prevent.", "Internal — \`lib/catalog.ts\` (\`isEntityIndexable\`, \`isPublicIndexableComparison\`). The real gate functions."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "corrections": {
    title: "Corrections",
    description: "How BestAIAgent.in actually records corrections: dated changelog entries and lastReviewed updates, not a separate fictional correction log.",
    blocks: [
      { type: "p", text: "This site doesn't maintain a separate correction log with its own severity taxonomy and lifecycle states — that system was described on an earlier version of this page but was never actually built. The real mechanism is simpler and already public." },
      { type: "h2", text: "Where corrections actually show up" },
      { type: "ul", items: ["**The changelog** — [](/changelog) records real, dated releases, and carries a standing disclosure that historical entries may describe systems (like the old scoring model) that were later retired — so a reader doesn't mistake an old release note for a current capability.", "**A page's own \`lastReviewed\` date** — when an authority page's content is corrected, its \`lastReviewed\` field is updated as part of that same change, in the same commit.", "**Entity re-verification** — if an evidence record turns out to be wrong, it's re-fetched and re-hashed, and the entity's evidence trail shows the new \`retrievedAt\` date."] },
      { type: "h2", text: "How to report a suspected error" },
      { type: "p", text: "This is a source-controlled, static site (see the README's \"What this is, and isn't\" section) — the most direct way to report or fix an error is a GitHub issue or pull request against the public repository, following \`CONTRIBUTING.md\`." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Freshness policy](/trust/freshness-policy)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`app/changelog/page.tsx\`. The real, live corrections/disclosure mechanism this page points to.", "Internal — \`CONTRIBUTING.md\`. The real contribution/correction path."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },
  "author-reviewer-policy": {
    title: "Author Attribution",
    description: "How BestAIAgent.in actually attributes content: git commit history in a public repository, not per-page named authors or reviewers.",
    blocks: [
      { type: "p", text: "This page previously described a per-page author/reviewer byline system with named editorial staff and a review board. No such system exists — pages don't carry \`author\`, \`reviewer\`, or \`nextReviewDue\` fields (the real \`AuthorityPage\` type in \`lib/authority-pages.ts\` has none of them). This page now says what's actually true." },
      { type: "h2", text: "The real attribution model" },
      { type: "p", text: "This is a static, source-controlled site. Every change to every page is a real, public, timestamped git commit in the project's GitHub repository, with a real author. That commit history — not a byline — is the actual record of who wrote or changed what, and it's more precise than a name in a page footer would be, since it's tied to the exact diff rather than a whole page." },
      { type: "h2", text: "Why there's no separate reviewer sign-off" },
      { type: "p", text: "For entity content, the evidence record itself (see [](/trust/evidence-methodology)) is the reviewable artifact — anyone can re-fetch the cited source and check the hash themselves, which is a stronger check than trusting a named reviewer's word. For editorial content, review happens through the same pull-request process as any other code change to this repository, documented in \`CONTRIBUTING.md\`." },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Editorial methodology](/trust/editorial-methodology)", "[Evidence methodology](/trust/evidence-methodology)", "[Corrections](/trust/corrections)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — \`lib/authority-pages.ts\` (\`AuthorityPage\` type). Confirms no author/reviewer fields exist.", "Internal — \`CONTRIBUTING.md\`. The real review process (pull requests against a public repository)."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-09-02"] },
    ]
  },

  "how-to-verify": {
    title: "How to Verify a Claim on BestAIAgent.in",
    description: "A practical, step-by-step guide to checking any claim on this site yourself, rather than taking a published field at face value.",
    blocks: [
      { type: "p", text: "Every other trust page on this site documents how we produce and gate content. This page is different: it's a walkthrough for you, the reader, on how to independently check whether a specific claim on a specific page actually holds up — in under a minute, using nothing but the page itself and its cited source." },
      { type: "h2", text: "Step 1: Find the receipt, not just the claim" },
      { type: "p", text: "On an entity page (an agent, model, framework or provider), look for the evidence block near the claim — it names a publisher, a retrieval date, and links to a primary source. If a field has no such block, it means the field is unknown by this site's own rule, not that the claim is unverified-but-true — treat it as genuinely unknown." },
      { type: "h2", text: "Step 2: Open the primary source directly" },
      { type: "p", text: "Click through to the linked source and read the passage yourself, rather than trusting our paraphrase of it. This matters most for anything volatile — price, plan limits, model version — since these can change after our retrieval date." },
      { type: "h2", text: "Step 3: Check the retrieval date against how fast the fact moves" },
      { type: "p", text: "A pricing fact retrieved 90 days ago is a different risk than an identity fact retrieved 90 days ago — see [](/trust/freshness-policy) for the specific re-verification windows we apply per claim type. If a page looks stale for its claim type, that's worth flagging as a correction rather than assuming it still holds." },
      { type: "h2", text: "Step 4: Distinguish a fact from an editorial judgment" },
      { type: "p", text: "A number with a citation is a fact. A recommendation, a \"best for X\" framing, or a comparative verdict is an editorial judgment built on top of facts — it should be labeled as such on the page. If a judgment reads like a fact with no methodology attached, that's a real defect worth reporting." },
      { type: "h2", text: "Step 5: Report what doesn't hold up" },
      { type: "p", text: "If a source doesn't say what the page claims it says, or the retrieval date is older than the freshness window for that claim type, use [](/trust/corrections) to report it with the specific field and the source you checked. This is the same reporting path a reviewer would use internally." },
      { type: "h2", text: "What verification does not mean" },
      { type: "ul", items: ["A verified identity does not mean every field on that entity's page is verified — verification is field-level, not whole-page.", "A primary source can still be wrong; verification confirms we cited it accurately, not that the source itself is infallible.", "An evidence-ready comparison does not mean a universal winner — see [](/trust/comparison-methodology) for what a comparison page does and doesn't assert."] },
      { type: "h2", text: "Related methodology pages" },
      { type: "ul", items: ["[Evidence methodology](/trust/evidence-methodology)", "[Source classification](/trust/source-classification)", "[Freshness policy](/trust/freshness-policy)", "[Corrections](/trust/corrections)", "[Rating methodology](/trust/rating-methodology)"] },
      { type: "h2", text: "Source receipts" },
      { type: "ul", items: ["Internal — [Evidence methodology](/trust/evidence-methodology) (this site, retrieved 2026-08-29). The receipt structure this page teaches readers to check."] },
      { type: "h2", text: "Last reviewed" },
      { type: "ul", items: ["Page last reviewed: 2026-08-29", "Next scheduled review: 2027-02-28"] },
    ]
  },
};
